### PR TITLE
More statistical functions added to stats.js (2)

### PR DESCRIPTION
**Pull request by riya-patil**
# Description

The following functions have been added into stats.js:
Geometric Distribution (PDF)
Binomial Distribution
Binomial Coefficient
Log Series Distribution
Lognormal Distribution (PDF)
Gumbel Distribution 
Uniform Distribution
Linear Moving Average

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x]  Chrome browser testing: using Inspect element, I used the console to test all the functions I'm implementing by making an instance of HydroLang and calling the function for a result.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by erazocar — CHANGES_REQUESTED** [review]
**General**
Keep standard structure of description and examples as follows:
```js
/**
Description of the method
@method functionName
...
@example
const data = [someData]
const params = {someParams}
hydro.analyze.stats.fuctionName(//...)
*/
```

**Log Series**
Log series distributions is incorrect. See attached:

```js
logSeriesDist({ params, args, data }) {
  //...
  const pmf = -Math.log(1 - probSuccess) * Math.pow(probSuccess, trials) / trials;
  return pmf;
}
```
**Gumbel**
Move the `x` to `args`, just as in the rest of the distributions.

**Linear moving average**
- This is the implementation of a simple moving average. Let's rename this function as such. 
- Move the data to the `data` parameter instead of `args`.
- The `@example` tag should be as other implementations. e.g. `hydro.analyze.stats.simpleMovingAverage({params: {windowSize}, data}})`

**Comment by riya-patil** [comment]
# Description

The following functions have been added into stats.js:
Homogenous Poisson Process
Non-Homogenous Poisson Process
Log Pearson Type III
boxPlotDistribution
Mean Squared Error
Exponential Moving Average
Return Period
Multinomial Distribution

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x]  Chrome browser testing: using Inspect element, I used the console to test all the functions I'm implementing by making an instance of HydroLang and calling the function for a result.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules# Description

The following new functions have been added into stats.js:
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Homogenous Poisson Process
--
Non-Homogenous Poisson Process
Log Pearson Type III
boxPlotDistribution
Mean Squared Error
Exponential Moving Average
Return Period
Multinomial Distribution


</body>
</html>

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x]  Chrome browser testing: using Inspect element, I used the console to test all the functions I'm implementing by making an instance of HydroLang and calling the function for a result.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

**Review by erazocar — CHANGES_REQUESTED** [review]
**General**
- Keep consistency on the comments. Example:
```js
/**
* This is a description of the function, thorough or simple depending on the function.
* @method nameOfFunction
* ...
*/
```

**Multinomial Distribution**
There is an error with the distribution. Frequencies should account for repetition of numbers, the function copies the same numbers as samples.

Consider the following changes:
```js
static multinomialDistribution({ params, args, data }) {
   //...
  for (let i = 0; i < n; i++) {
    const sample = [];
    const frequency = Array(numCategories).fill(0);//delete this
    //...
    frequencies.push(this.frequency({data: sample}));//there is already a function for calculating frequencies
  }
  return { samples, frequencies };
}
```

**Expo Moving Average**
Move the data from `args` to `data` field and the `alpha` variable to `params`. Change the internal code accordingly.

```js
/**
 *const data= [1,2,3,4,5]
 *const params={alpha: 0.5}
 *hydro.analyze.stats.exponentialMovingAverage({params, data});
*/
```

**Poisson Process**
The implemented functions can be joined together passing a flag in the `params` object to switch the implementation type, defaulting to `homogeneous` if `type` is not passed.

Example implementation:
```js
static poissonProcess({ params, args }) {
  const { type = 'homogeneous', T } = params;
  const { lambda, rateFunction } = args;

  const events = [];
  let t = 0;

  while (t < T) {
    const rand = Math.random();
    const interTime = (type === 'homogeneous' ? -1 / lambda : -1 / rateFunction(t)) * Math.log(1 - rand);
    t += interTime;

    if (t < T) {
      if (type === 'homogeneous' || Math.random() <= rateFunction(t) / rateFunction(T)) {
        events.push(t);
      }
    }
  }

  return events;
}
```
Documentation would look something like this:
```js
/**
*Poisson process (more description here)
*...
*@param {Object} params - contains type: homogeneous or non homogeneous. Defaults to homogenous.
*@example
*Two examples, one for each test case
*/
```

**Boxplot Distribution**
Remove `data` parameter from the `example` as it isn't used.

**MSE**
Move the datasets into the `data` parameter.

**Comment by erazocar** [comment]
New functions on stats: Geometric Distribution (PDF), Binomial Distribution, Binomial Coefficient, Log Series Distribution, Lognormal Distribution (PDF), Gumbel Distribution, Uniform Distribution, Simple Moving Average

**Pull request merged**
